name: CI/CD Pipeline (Build and Deploy)
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - uses: actions/checkout@v3

      # 도커 빌드x 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker Hub에 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest

      # 서버에 배포
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 110.165.16.123
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Docker 로그인
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
            
            # 최신 이미지 풀
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest
            
            # 기존 컨테이너 중지 및 삭제
            docker stop my-app-container || true
            docker rm my-app-container || true
            
            # 새 컨테이너 실행
            docker run -d \
              --name my-app-container \
              -p 8080:8080 \
              ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest